---
- name: Restart SMB service
  ansible.builtin.service:
    name: "{{ smb_service }}"
    state: restarted

- name: Restart NMB service
  ansible.builtin.service:
    name: "{{ nmb_service }}"
    state: restarted
  when: not samba_disable_netbios
