---
samba_packages:
  - samba
  - samba-client

samba_vfs_packages: []

samba_configuration_dir: /etc/samba
samba_configuration: "{{ samba_configuration_dir }}/smb.conf"
samba_username_map_file: "{{ samba_configuration_dir }}/smbusers"

samba_services:
  - smb
  - nmb

samba_www_documentroot: /var/www/html
