---
galaxy_info:
  author: Bert Van Vreckem
  description: This role installs and configures Samba as a file server.
  license: BSD
  min_ansible_version: '2.11'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: Debian
      versions:
        - bullseye
        - buster
  galaxy_tags:
    - system
    - networking
dependencies: []
